# 自定义报告顶部显示的环境/标题信息
Project_Name=搜狗首页元素自动化测试
Test_Module=Sogou Homepage Elements Test
Test_Environment=Local Windows 10
Python_Version=3.14.3
Selenium_Version=4.41.0
Allure_Version=2.15.3
Test_Date=2026-03-18